require('powy.remap')
require('powy.harpoon')
require('powy.undotree')
require('powy.trouble')
require('powy.borders')
require('powy.indent')
-- require("powy.format")
require('powy.null-ls')
-- require 'powy.notify'
require('powy.theme')
require('powy.nvterm')
